[tool.black]
line-length = 100

[build-system]
requires = [
    "setuptools>=42, <65",
    "wheel",
    "scikit-build>=0.13.1",
    "Cython>=0.24",
    "scipy>=0.16"
]
build-backend = "setuptools.build_meta"
